CREATE TABLE CLIENTE (
	CPF NUMERIC (11) NOT NULL PRIMARY KEY,
    NOME VARCHAR (30) NOT NULL,
    FONE NUMERIC (11) NOT NULL
);

CREATE TABLE CARRO (
	COD VARCHAR (4) NOT NULL PRIMARY KEY,
	MODELO VARCHAR (30) NOT NULL,
    VALOR FLOAT (6) NOT NULL
);

CREATE TABLE COMPRA (
	COD INT (3) NOT NULL PRIMARY KEY,
    VALOR FLOAT (6) NOT NULL,
    CPF NUMERIC (11) NOT NULL,
    COD_C VARCHAR (4) NOT NULL,
	CONSTRAINT FK_CLIENTE FOREIGN KEY (CPF) REFERENCES CLIENTE (CPF),
    CONSTRAINT FK_CARRO FOREIGN KEY (COD_C) REFERENCES CARRO (COD)
);

INSERT INTO CLIENTE (CPF, NOME, FONE) VALUES (99999999999, "João", 47999999999);
INSERT INTO CARRO (COD, MODELO, VALOR) VALUES ("BMW0", "X0", 1000.00);
INSERT INTO COMPRA (COD, VALOR, CPF, COD_C) VALUES (100, 2000.00, 99999999999, "BMW0");

SELECT * FROM CLIENTE;