USE PROJETO;

SELECT * FROM CLIENTE;
SELECT * FROM PF;
SELECT * FROM PJ;

-- ---------------------------------------------------------------------------------------

-- MIN AND MAX
SELECT MIN(ID), MAX(ID) FROM CLIENTE; -- PARA MOSTRAR O MENOR E O MAIOR VALOR DE UMA COLUNA

-- COUNT
SELECT COUNT(ID)
FROM CLIENTE; -- PARA VISUALIZAR A QUANTIDADE DE VALORES DE UMA COLUNA

-- INNER JOIN
SELECT CLIENTE.FONE, PF.NOME, PF.APELIDO
FROM CLIENTE
INNER JOIN PF
ON CLIENTE.ID = PF.FK_ID_PF; -- SELECT PARA VISUALIZAR OS DADOS QUE ESTÃO EM DUAS TABELAS (GERALMENTE FK)

SELECT PJ.RAZAO_SOCIAL, CLIENTE.FONE
FROM PJ
INNER JOIN CLIENTE
ON PJ.FK_ID_PJ = CLIENTE.ID
WHERE PJ.RAZAO_SOCIAL = "Totvs"; -- USANDO INNER JOIN COM FILTROS MAIS ESPECÍFICOS (CUIDAR COM O CASE SENSITIVE DA BUSCA DO WHERE)

