CREATE TABLE CARRO (
	CHASSI VARCHAR (17) NOT NULL PRIMARY KEY,
	MODELO VARCHAR (50) NOT NULL,
	PRECO FLOAT (10) NOT NULL
);

CREATE TABLE CLIENTE (
	CPF NUMERIC (11) NOT NULL PRIMARY KEY,
    NOME VARCHAR (50) NOT NULL,
    SOBRENOME VARCHAR (50) NOT NULL,
    IDADE NUMERIC (3) NOT NULL,
    TELEFONE NUMERIC (11) NOT NULL,
    DDD NUMERIC (3) NOT NULL,
    OPERADORA VARCHAR (30) NOT NULL
);

CREATE TABLE COMPRA (
	ID_COMPRA NUMERIC (5) NOT NULL PRIMARY KEY,
    VALOR FLOAT (10) NOT NULL,
    CPF NUMERIC (11) NOT NULL,
    CHASSI VARCHAR (17) NOT NULL,
    CONSTRAINT FK_COMPRA_CLIENTE FOREIGN KEY (CPF) REFERENCES CLIENTE (CPF),
    CONSTRAINT FK_COMPRA_CARRO FOREIGN KEY (CHASSI) REFERENCES CARRO (CHASSI)
);

INSERT INTO CARRO (CHASSI, MODELO, PRECO) VALUES ('A10', 'KWID', 999);

INSERT INTO CLIENTE (CPF, NOME, SOBRENOME, IDADE, TELEFONE, DDD, OPERADORA) VALUES (12345678910, 'MATHEUS', 'POMPEO', 17, 47991884778, 047, 'VIVO');

INSERT INTO COMPRA (ID_COMPRA, VALOR, CPF, CHASSI) VALUES (10, 10000.00, 12345678910, 'A10');

SELECT * FROM CARRO