CREATE TABLE VEICULO (
	NUMERO_DE_SERIE VARCHAR (35) NOT NULL PRIMARY KEY,
    MARCA VARCHAR (35) NOT NULL,
    MODELO VARCHAR (35) NOT NULL,
    ANO_DE_FABRICACAO DATE NOT NULL,
    COR VARCHAR (20) NOT NULL
);

CREATE TABLE CARRO (
	SERIE_CARRO VARCHAR (35) NOT NULL PRIMARY KEY,
    NOME_DE_PORTAS NUMERIC (1) NOT NULL,
    FK_CARRO_VEICULO_NUMERO_DE_SERIE VARCHAR (35) NOT NULL,
	CONSTRAINT FK_CARRO_VEICULO_NUMERO_DE_SERIE  FOREIGN KEY (FK_CARRO_VEICULO_NUMERO_DE_SERIE  ) REFERENCES VEICULO (NUMERO_DE_SERIE)
);

CREATE TABLE MOTO (
	SERIE_MOTO NUMERIC (10) NOT NULL PRIMARY KEY,
    TIPO_DE_MOTOR VARCHAR(35) NOT NULL,
    FK_MOTO_VEICULO_NUMERO_DE_SERIE VARCHAR (35) NOT NULL,
    CONSTRAINT FK_MOTO_VEICULO_NUMERO_DE_SERIE FOREIGN KEY (FK_MOTO_VEICULO_NUMERO_DE_SERIE ) REFERENCES VEICULO (NUMERO_DE_SERIE)
);

CREATE TABLE CLIENTE (
	MATRICULA VARCHAR (35) NOT NULL PRIMARY KEY,
    NOME VARCHAR (35) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL
);

CREATE TABLE PESSOA_JURIDICA (
	CNPJ NUMERIC (14) NOT NULL PRIMARY KEY,
	FK_PJ_CLIENTE_MATRICULA VARCHAR (35) NOT NULL,
    CONSTRAINT FK_PJ_CLIENTE_MATRICULA  FOREIGN KEY (FK_PJ_CLIENTE_MATRICULA ) REFERENCES CLIENTE (MATRICULA)
);

CREATE TABLE PESSOA_FISICA (
	CPF NUMERIC (11) NOT NULL PRIMARY KEY,
	FK_PF_CLIENTE_MATRICULA VARCHAR (35) NOT NULL,
    CONSTRAINT FK_PF_CLIENTE_MATRICULA  FOREIGN KEY (FK_PF_CLIENTE_MATRICULA ) REFERENCES CLIENTE (MATRICULA)
);

CREATE TABLE COMPRA (
	FK_CLIENTE_MATRICULA VARCHAR (35) NOT NULL PRIMARY KEY,
	FK_VEICULO_NUMERO_DE_SERIE VARCHAR (35) NOT NULL,
    CONSTRAINT FK_CLIENTE_MATRICULA FOREIGN KEY (FK_CLIENTE_MATRICULA ) REFERENCES CLIENTE (MATRICULA),
    CONSTRAINT FK_VEICULO_NUMERO_DE_SERIE FOREIGN KEY (FK_VEICULO_NUMERO_DE_SERIE ) REFERENCES VEICULO (NUMERO_DE_SERIE)
);