DROP SCHEMA IF EXISTS BIBLIOTECA;
CREATE SCHEMA BIBLIOTECA;
USE BIBLIOTECA;

CREATE TABLE USUARIO (
    CODUSUARIO NUMERIC(5) NOT NULL PRIMARY KEY,
    LOGIN VARCHAR(50) NOT NULL,
    SENHA VARCHAR(20) NOT NULL,
    PERFIL NUMERIC(1) NOT NULL
);

CREATE TABLE ESTUDANTE (
    MATRICULA NUMERIC(5) NOT NULL PRIMARY KEY,
    NOMECOMPLETO VARCHAR(100) NOT NULL,
    DATANASCIMENTO DATE NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONE NUMERIC(11) NOT NULL
);

ALTER TABLE ESTUDANTE 
ADD FOREIGN KEY (MATRICULA) 
REFERENCES USUARIO (CODUSUARIO);

CREATE TABLE LIVRO (
    CODLIVRO NUMERIC(5) NOT NULL PRIMARY KEY,
    TITULO VARCHAR(100) NOT NULL,
    AUTOR VARCHAR(100) NOT NULL,
    ANO NUMERIC(4) NOT NULL,
    EDITORA VARCHAR(50) NOT NULL
);

CREATE TABLE EMPRESTIMO (
    CODEMPRESTIMO NUMERIC(5) NOT NULL PRIMARY KEY,
    DATAENTRADA DATE NOT NULL,
    DATARETIRADA DATE NOT NULL,
    DEVOLUCAO VARCHAR(2),
    MATRICULA NUMERIC(5) NOT NULL,
    CODLIVRO NUMERIC(5) NOT NULL
);

ALTER TABLE EMPRESTIMO 
ADD FOREIGN KEY (MATRICULA) 
REFERENCES ESTUDANTE (MATRICULA);

ALTER TABLE EMPRESTIMO 
ADD FOREIGN KEY (CODLIVRO) 
REFERENCES LIVRO (CODLIVRO);
